project:
  type: website
website:
  title: "NionMaron"
  site-url: https://nionmaron.com
  favicon: "images/site_icon.png"
  page-footer:
    center: "Developed by [Nion M. Dransfeld](https://nionmaron.com) <br> Powered by [Quarto](https://quarto.org/)"
    border: false
    background: light
  navbar:
    background: "#2E8BC0" # / Ref: https://www.canva.com/colors/color-palettes/mermaid-lagoon/
    right:
      - text: "Blog"
        file: Blog.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/nionmaron/?locale=en_US
      - icon: github
        href: https://github.com/nionmaron
format:
  html:
    mainfont: Corn # MADE Gentle # Sans-serif
    theme:
      light: cosmo
      dark: darkly
      
    
    css: styles.css

editor: visual

