project:
  type: website
  resources:
    - ads.txt # add adsense
website:
  title: "NionMaron"
  site-url: https://nionmaron.com
  favicon: "images/site_icon.png"
  twitter-card: true
  open-graph: true #specification that enables richer sharing of links to articles on the web
  google-analytics: "G-PGRFF9TPBC"
  
  page-footer:
    background: "#005f73"
    #background: light
    left: |
      Developed by [Nion M. Dransfeld](https://nionmaron.com)
    center: | 
      [Edit this page]( https://github.com/nionmaron/Website-NionMaron/) <br> [Report an issue](https://github.com/nionmaron/Website-NionMaron/issues)
    right: |
      [Terms & Conditions](/ts-and-cs.qmd)
    #border: false
    
  navbar:
    background: "#005f73" # / Ref: https://www.canva.com/colors/color-palettes/mermaid-lagoon/
    right:
      - text: "Blog"
        file: Blog.qmd
      - text: "Flashcards"
        menu:
        - text: "Machine Learning"
          file: Machine-Learning-Flashcards.qmd
        - text: "Data Science"
          file: Data-Science-Flashcards.qmd
          
      - text: "About Me"
        menu:
        - text: "My Resume"
          href: https://resume.nionmaron.com/
        - text: "Portfolio"
          file: Portfolio.qmd
        - text: "Journey"
          file: CV.qmd
        - icon: linkedin
          href: https://www.linkedin.com/in/nionmaron/?locale=en_US
        - icon: github
          href: https://github.com/nionmaron


format:
  html:
    theme: minty
    #mainfont: "Montserrat"
    css:
      - CSS/styles.css
      - CSS/Buttons.css

editor: visual

execute: 
  freeze: auto