project:
  type: website
  resources:
    - ads.txt # add adsense
website:
  title: "NionMaron"
  site-url: https://nionmaron.com
  favicon: "images/site_icon.png"
  twitter-card: true
  open-graph: true #specification that enables richer sharing of links to articles on the web
   
  page-footer:
    background: "#000000"
    #background: light
    left: |
      Copyright &copy; 2023 [NionMaron](https://github.com/nionmaron/Website-NionMaron/blob/master/LICENSE.md)
    center: | 
      Developed by [Nion M. Dransfeld](https://nionmaron.com) 
      <br> [Edit this page]( https://github.com/nionmaron/Website-NionMaron/) | [Report an issue](https://github.com/nionmaron/Website-NionMaron/issues)
    right: |
      [Terms & Conditions](/ts-and-cs.qmd)
    border: false
    
  navbar:
    background: "#2E8BC0" # / Ref: https://www.canva.com/colors/color-palettes/mermaid-lagoon/
    right:
      - text: "Blog"
        file: Blog.qmd
      - text: "Portfolio"
        file: Portfolio.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/nionmaron/?locale=en_US
      - icon: github
        href: https://github.com/nionmaron
format:
  html:
    mainfont: Corn # MADE Gentle # Sans-serif
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
      
    css: styles.css

editor: visual

execute: 
  freeze: auto