---
title: "Terms and conditions"
page-layout: article
sidebar: false
toc: true
title-block-banner: true
---

## Legal disclaimer

Statements of fact and opinion published on this website are those of the respective authors and contributors.

The NionMaron website's content is created with responsibility and care. However, the blog disclaims all warranties, express and implied, regarding the accuracy of the information in its materials and on linked sites. The NionMaron website and its linked content are provided as-is. We do not guarantee the accuracy or reliability of the information. This disclaimer covers:

-   any implied warranties of merchantability and fitness for a particular purpose.

-   any liability for damage to your computer hardware, data, information, materials and business resulting from the information or the lack of information available.

-   any errors, omissions, or inaccuracies in the information.

-   any decision made or action taken or not taken in reliance upon the information.

By using this site, you agree to these terms and conditions of use.

## Site content

Where licence terms for individual articles, videos, images and other published content permit republication, you may do so in accordance with the stated terms of the respective licence(s).

You are not permitted to republish this site in its entirety.

## Software and services

Source code and files for this site are available from [GitHub](https://github.com/nionmaron/Website-NionMaron).

This site is built using [Quarto](https://quarto.org/), an open-source scientific and technical publishing system developed by [Posit](https://posit.co/). Quarto source code and software licences are available from [GitHub](https://github.com/quarto-dev).

NionMaron is hosted by [Netlify](https://www.netlify.com/).
